# Numpy Arrays

In [1]:
import numpy as np

In [3]:
# how to create a numpy array, one way we can do this by directly transforming or converting a python list

mylist = [1, 2, 3] # standard python list

In [4]:
type(mylist)

list

In [6]:
# so to transform it we can do

np.array(mylist) # now a numpy array is output

array([1, 2, 3])

In [7]:
# doesnt affect original list, it will remain a python list like we know
mylist

[1, 2, 3]

In [8]:
# we would have to reassign it to something like 

numpylist = np.array(mylist)

numpylist

array([1, 2, 3])

In [9]:
# to confirm we can type check the reassignment
type(numpylist)

numpy.ndarray

In [12]:
# So what we worked on was a one dimensional array, we can also do this for a two dimensional array. Here is an example:

my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] # 3 items in a list, normal python list

In [13]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
# lets pass it as a numpy array

np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Numpy digests it as a 2 dimensional array, where it is seen as 3 rows and 3 columns. This is key to Numpy to manipulate and have capabilites/functions applied to 2 dimensional data sets. 

We will also be using built in methods and functions within Numpy over the usual standard Python library.

In [15]:
# One of the useful ones is:

# this is range, not arrange but 'a range'
np.arange(0, 10) # start 0 and go to 10 but don't include 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# we can also use step size in numpy too

np.arange(0, 10, 2) # start from 0, go to but not including 10, step every 2 numbers. 

array([0, 2, 4, 6, 8])

Common to have to create large arrays of 0's and 1's when dealing with realistic datasets.    

In [29]:
np.zeros(5) # produces 5 amount of 0's as a 1 dimensional vector, which consists of 0's as floats (floating point number)

# note when you see something taking in data as a "shape", it means it's the dimensions of a matrix via tuple. Below are some examples.

array([0., 0., 0., 0., 0.])

In [25]:
# if we want 2 dimensional
# pass in as a tuple 
np.zeros((5, 5)) # returns 5 rows and 5 columns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
# say you want 5 columns but 2 rows
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
# or say you want 3 rows but 2 columns
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [32]:
# we can also do the same thing as 0's but with 1's.
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
# same as the 1 dimensional vector if only passed a value 
np.ones(12) # 12 one's in a vector

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [41]:
# linspace returns evenly spaced numbers over a specified interval, don't confuse it with numpy arange

np.linspace(0, 10, 5) # the num which is the third value will return say in our example 5 values, evenly spaced between start 0 and stop 10.

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [45]:
np.linspace(0, 10, 11)
# 11 outputs all 0 to 10 (not 1 - 10 of 10 values it is 11 values altogether) since it includes endpoint unlike the normal range or arange. 

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [48]:
# eye function, creates the identity matrix

np.eye(5) # called identity matrix due to equal number of rows and columns with the 1 along the diagonal

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Now focusing on discovering and how to create random distributions of data. There are many to choose from but here are a few:

In [50]:
# just type np.random. + 'tab key', it will list many options

# first one

np.random.rand(1) # will return a number that falls between 0 and 1 

array([0.89647688])

In [54]:
# if you wish to pass in shape
np.random.rand(3, 4) # 3 by 4, all numbers between 0 and 1

array([[0.74501884, 0.68329088, 0.13683211, 0.75628881],
       [0.13242453, 0.69480729, 0.99499056, 0.41991423],
       [0.57920755, 0.70142906, 0.94446091, 0.74063258]])

In [60]:
# in the physical real world, things fall under normal distribution. A simplified version of a normal distribution is a standard normal distribution

# np.random.randn, include n at the end of rand.

np.random.randn(4)
# this will return amount of numbers.
# Notice we will get negative numbers. Numbers that are closest to 0 have a higher rate of being selected
# than numbers further and further away from it.

array([-0.18682628,  0.66024834, -0.20302121,  0.35629043])

In [61]:
# you can also ask for these numbers in a particular shape

np.random.randn(2, 3)

array([[-0.64752018, -1.30049352, -1.06352112],
       [ 1.01398814, -1.81249861,  0.05096641]])

So this is returning samples from a standard normal distribution. Because it's standard normal,  values closer to 0 are more likely to appear than values further away from 0.

In [69]:
# here is another one
# np.random.randint(), you can tell it returns random integers

np.random.randint(0, 101, 10) # returns 0 to 101 range of random numbers, returns 10 numbers within that range

array([29, 60, 44, 99, 40, 17, 24, 12, 72, 11], dtype=int32)

In [71]:
np.random.randint(0, 101, (5, 5)) # this way it returns a 5D where 5 rows and 5 columns are generated randomly

array([[48, 18, 93, 59, 39],
       [77, 48, 91, 85, 46],
       [32, 61, 44, 12, 13],
       [38, 40, 90, 73, 60],
       [54, 40, 65, 54, 90]], dtype=int32)

When you're using random data and you run different tests on it, it's very useful to be able to set a seed. A seed is used to set a random state so that the random results can be reproduced. Results are still random, but you are choosing an arbitrary seed number, so you get a particular set of random numbers. 

In [74]:
# to do this you do

# arbitrary number choice is 42 by default used in a lot of python libraries
np.random.seed(42)  # so this is setting the seed

# now call it, MAKE SURE ITS IN THE SAME CELL
np.random.rand(4) # after setting seed we ask for 4 random numbers between 0 and 1

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

The seed is not a container that holds the random numbers. Instead, the seed is the starting point for the math formula that creates them.

Think of it like a book:
The Seed is the Page Number.
The Random Numbers are the Sentences on that page.

If you tell NumPy to start at "Page 10" (Seed 10), and read the next 5 sentences (5 random numbers), those sentences will be the same every time you open the book to that page. The value 5 is just the count of how many numbers you want, not where they are stored.

If you set the seed to 10 and ask for 5 numbers, you get the same 5 numbers every time because you started the "math" at the same point (10).

#### Couple more useful methods and attributes you can oftenly perform on existing NumPy array 

In [79]:
# say we have a range of 0 - 24
arr = np.arange(0, 25)

In [80]:
arr # check 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [84]:
# we can reshape arr, aka the range of numbers
arr.reshape(5, 5) # here we reshape it 5 by 5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

One common mistakes that occur is when reshaping or shaping range of numbers where it wont fit. Say we use the same 25 numbers, if we try 5 by 4, that is 20 numbers in total since 5 x 4 = 20, but that is 5 more numbers that will not fit within the shape or rows/columns correctly. 

In [85]:
# lets check it out to prove that it won't work

arr.reshape(5, 4)

ValueError: cannot reshape array of size 25 into shape (5,4)

Here we got an error where it states, "cannot reshape array of size 25 into shape (5,4)". So keep in mind the number of rows and columsn before you squeeze in an array of numbers where it won't fit. 

#### Max, Min, Argmax and Argmin

In [90]:
rand_array = np.random.randint(0, 101, 10) # generate random 10 numbers within 0 - 100

In [92]:
rand_array

array([10, 80,  7, 34, 34, 32,  4, 40, 27,  6], dtype=int32)

In [95]:
rand_array.max() # returns the max in vector

np.int32(80)

In [96]:
rand_array.min() # returns the in in vector

np.int32(4)

In [97]:
rand_array.argmax() # returns the index value of max

np.int64(1)

In [98]:
rand_array.argmin() # returns the index value of min

np.int64(6)

In [100]:
rand_array.dtype # data type and bit whether its 32 or 64 bit

dtype('int32')

In [102]:
# if you want to know say rand_arrays shape

rand_array.shape

(10,)

In [104]:
# if you then reassign it like
rand_array = rand_array.reshape(5, 2)

In [105]:
rand_array

array([[10, 80],
       [ 7, 34],
       [34, 32],
       [ 4, 40],
       [27,  6]], dtype=int32)

In [107]:
rand_array.shape # you can then check shape 

(5, 2)

Just to clarify, why earlier when we had an array and we check its shape before reshaped, it wsa just 10, with a comma only. That is to indicate that it is one dimensional. 