#  Indexing and Selection

In [1]:
import numpy as np

### Selection

In [2]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
# we established our array range of 0 to 11 consisting of values from 0 - 10.
# to select a single value 

arr[8] # should output 8

np.int64(8)

In [8]:
# so lets say we want to get specific set of values 
arr[1:5] # [start : up to but not including]

array([1, 2, 3, 4])

In [10]:
# if you want to start from the very beginning

arr[0:5]

array([0, 1, 2, 3, 4])

In [12]:
 # You can also omit the 0 and it is the start of the array
arr[:5] # same results as having 0

array([0, 1, 2, 3, 4])

In [13]:
# same thing when you omit the end value
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

### Broadcasting

NumPy arrays can broadcast, meaning they can take a single value and automatically apply it to many elements at once. In normal Python lists, if you want to replace multiple elements, you must provide the same number of new elements. With NumPy, you can assign just one value and NumPy will automatically repeat it across the selected part of the array.

In [14]:
# here is an example
# so we have our array 0 - 10
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
arr[:5] = 100

Here we assign the first 0 - 5 indexed elements to equal 100, so we broadcast 100 over those selected elements.

In [19]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [21]:
# lets just reset this again

arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

When you slice a NumPy array and store it in another variable, NumPy usually does NOT create a new array. Instead, it creates a view (a pointer) to the same original data in memory.

When you slice a NumPy array and assign it to a new variable, that new variable points to the same data in memory. Because of that, changing the slice also changes the original array.

In simple terms:
The slice is not a separate copy, it’s just another view of the original array, so any modification to it will affect the original array as well.

In [23]:
# here is an example

arr_slice = arr[0:5] # slicing array from 0 - 4 values

In [24]:
# lets check our sliced array

arr_slice

array([0, 1, 2, 3, 4])

In [25]:
# now lets say we select everything in that slice from the original array held in "arr", and broadcast their values to be 117 (for the halo fans). 
# that should update not only for this arr_slice, but the original array variable held in "arr".
arr_slice[:] = 117

In [26]:
# now lets check our arr_slice

arr_slice

array([117, 117, 117, 117, 117])

In [27]:
# since that slice has been updated, lets see our original array, "arr".
arr

array([117, 117, 117, 117, 117,   5,   6,   7,   8,   9,  10])

So as you can see, the NumPy array has been sliced, updated the slice to 117 from 0 to 4, which was then applied to the original array where we can see the output has changed. Key thing again, it is just a pointer, not a copy or any new created array. Just a referencing point which is actually the original. 

Moreover, broadcasting saves memory over the original Pythons method when updating the elements.

### What if you didn't want to affect the original array?

Well, you will need to explicitly set a copy of the array.

In [29]:
arr_copy = arr.copy() # so this creates the copy of an array, duplicating the original which also means more memory usage

In [30]:
arr_copy

array([117, 117, 117, 117, 117,   5,   6,   7,   8,   9,  10])

In [31]:
# to test that the original remains untouched when changes are being made, lets make all elements 100.
arr_copy[:] = 100

In [32]:
# lets check that it updated in arr_copy
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [33]:
# okay now that its updated, lets check our original array
arr

array([117, 117, 117, 117, 117,   5,   6,   7,   8,   9,  10])

#### So you can see, when you set a copy and reassign it into a new variable, the original will not be touched. 

#### HOWEVER, if you reassign it into a new variable BUT YOU DO NOT SET COPY, then the original array will be affected to manipulation. 

### Indexing on 2D arrays/matrices

In [38]:
array_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 46]])
# REMINDER: remember, this is essentially a list of 3 lists (nested list), which is transformed into a numpy array via np.array 

In [39]:
array_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 46]])

In [42]:
array_2d.shape # returns number of (row, columns)

(3, 3)

In [44]:
# lets say we just want to grab a single row

array_2d[0] # so we are using index to grab the rows, so index 0 holds row 1.

array([ 5, 10, 15])

In [45]:
# if we want row 3, we choose index 2

array_2d[2]

array([35, 40, 46])

In [48]:
# say you want to grab 25. thats in row index 1, column index 1. theres 2 ways you can do this
array_2d[1][1] # method 1

np.int64(25)

In [49]:
# this method is MUCH preferred over the previous one
array_2d[1, 1] # basically means [row 1, column 1]

np.int64(25)

In [50]:
# we can also use slicing. say we want to get 10 and 15 from the first row, then 25 and 30 from the second row.

array_2d[:2] # first we grap the rows we want, we omit 0 and up to but not including 2. this grabs first 2 rows

array([[ 5, 10, 15],
       [20, 25, 30]])

We got our sliced target selection. So now we separate with a comma after 2 from when we sliced, then add 1 since that is the start of the column where 10 is (which will ignore the first column of 5 and 20 from first and second row) and omit the end value with just colon to go till the end since we need both 15 and 30 which are the end of the columns.

In [53]:
array_2d[:2, 1:] 

array([[10, 15],
       [25, 30]])

## Conditional Selection

This selection is much more commonly used.

In [54]:
# example

arr = np.arange(1, 11)

In [55]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
# you can broadcast a condition, like wheres my array greater than 4?

arr > 4 # this will output a boolean result where elements that are greater than 4 will return true, else false. so that is any number 4 or below

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [62]:
bool_arr = arr > 4 # assign the condition

In [59]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [63]:
arr[bool_arr] # you can then filter by passing it to the original array

array([ 5,  6,  7,  8,  9, 10])

In [64]:
arr[arr > 4] # you can also filter by passing condition through original array too.

array([ 5,  6,  7,  8,  9, 10])

### arr[arr > 4] <-- This is the conditional selection or sort of thing we will see quite often, especially when you progress towards Pandas. Pandas will then later give us the ability to do multiple comparisons.