# Numpy Operations

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# if we do + 5 to arr like: arr + 5, it will apply to all the elements in the array
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
# we can do the same thing for minus, say - 10
arr - 10

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

#### We can also apply operations to itself or against other arrays, but do keep in mind arrays MUST be the same shape! 

In [6]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

You can tell by now you can do it for any operation, including multiplication and division.

In [7]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [9]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Numpy deals with 0's differently in division. It will throw some sort of warning or error if your array includes 0.

In [10]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr / arr

C:\Users\birah\AppData\Local\Temp\ipykernel_244\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

As you can see, we got that warning message: "RuntimeWarning: invalid value encountered in divide
  arr / arr".

It will still output the value regardless.

When you do this in python you get returned a ZeroDivisionError, but in mumpy you will get a warning and an output, as well as the division by 0 being returned as infinite.

In [13]:
1 / 0 # regular python will throw out an error

ZeroDivisionError: division by zero

In [16]:
1 / arr # division with numpy array where first value output is inf for infinite where 0 was, where 1 / 0. 

C:\Users\birah\AppData\Local\Temp\ipykernel_244\3420005425.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr # division with numpy array where first value output is inf for infinite where 0 was, where 1 / 0.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

The risk with this is, is that regardless of the problem, NumPy will keep on running the program despite the issues occuring. 

#### There are many other further operations NumPy can do. Let us check them out.

In [17]:
# square root
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [18]:
# trigonometric functions like sin for example
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [19]:
# perhaps log for logarithm
np.log(arr)

C:\Users\birah\AppData\Local\Temp\ipykernel_244\1258389937.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

Same thing occuring due to the 0 causing warnings when passed into the log function.

A lot of summary statistics on arrays over these types of functions. Really large datasets are often dealt with and you want to perform summary on stats in order to get an idea of the general intuition behind the dataset.

In [23]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
# sum is one, but we've seen this before
arr.sum()

np.int64(45)

In [25]:
# get the mean of the array data
arr.mean()

np.float64(4.5)

In [26]:
# or the max aka highest value
arr.max()

np.int64(9)

There are other things like variance and standard deviation built into NumPy.

In [29]:
# variance
arr.var()

np.float64(8.25)

In [30]:
# standard deviation or SD
arr.std()

np.float64(2.8722813232690143)

#### Let's create a 2D (2 Dimensional) Array

In [32]:
arr2d = np.arange(0, 25).reshape(5, 5)

In [38]:
arr2d.shape

(5, 5)

In [39]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [40]:
arr2d.sum()

np.int64(300)

When you shift + tab on say sum(), you can read "a.sum(axis=None, dtype=None, out=None, keepdims=False, initial=0, where=True)".

You notice that sum actually takes in an axes parameter, which means you can specify whether you want to perform this operation across the rows or across the columns. Key word being across.

In [43]:
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

So on axis=0, we get our first value being 50. This is the sum of the first column across the rows. We go from first row + row 2 + row 3 ... until the last row, sum all the values of which we said is 50. We do this across all columns on axis 0. 

In [46]:
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])

When axis=1, we can see this time, we go across all columns, not rows. We go across all columns per row and get the sum. We can see in our first row, if we sum the values across all columns again from the first row, we get 10. 4 + 3 + 2 + 1 = 10. 

# KEY TAKEAWAY
## Axis = 0: Across the rows
## Axis = 1: Across the columns